//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Anything
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExchangeRate
    {
        public int Id { get; set; }
        public int ExchangeFromId { get; set; }
        public int ExchangeToId { get; set; }
        public double Rate { get; set; }
        public int MoneyChangerId { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
    
        public virtual Currency Currency { get; set; }
        public virtual Currency Currency1 { get; set; }
        public virtual MoneyChanger MoneyChanger { get; set; }
    }
}
