//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Anything
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoricalRate
    {
        public int Id { get; set; }
        public Nullable<int> ExchangeFromId { get; set; }
        public Nullable<int> ExchangeToId { get; set; }
        public double Rate { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Currency Currency { get; set; }
        public virtual Currency Currency1 { get; set; }
    }
}
